services:
  init:
    build:
      context: init
    env_file: .env
    volumes:
      - type: volume
        source: minecraft-dir
        target: /mnt/minecraft
        volume:
          nocopy: true
  minecraft-server:
    build:
      context: minecraft-server
      args:
        MINECRAFT_VERSION: 1.18.2
    env_file: .env
    ports:
      - "25565:25565"
    restart: always
    volumes:
      - type: volume
        source: minecraft-dir
        target: /mnt/minecraft
        volume:
          nocopy: true
  send-command:
    build:
      context: send-command
    env_file: .env
    environment:
      RCON_HOSTNAME: minecraft-server

volumes:
  minecraft-dir:
