services:
  minecraft-server:
    build:
      context: minecraft-server
      args:
        MINECRAFT_VERSION: 1.20.1
    env_file: .env
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - type: bind
        source: ./world
        target: /mnt/minecraft
    tty: true
    stdin_open: true

  forge-server:
    build:
      context: forge-server
      args:
        MINECRAFT_VERSION: 1.20.1
    env_file: .env
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - type: bind
        source: ./forge-data
        target: /mnt/minecraft
    tty: true
    stdin_open: true

  mch:
    build:
      context: mch
      args:
        MINECRAFT_VERSION: 1.19.4
    env_file: .env
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - type: bind
        source: ./world
        target: /mnt/minecraft
    tty: true
    stdin_open: true
